"""adiciona campo colapsada em comanda

Revision ID: 18030d50ad1c
Revises: d68951206161
Create Date: 2026-07-06 17:09:34.652039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18030d50ad1c'
down_revision = 'd68951206161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colapsada', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.drop_column('colapsada')

    # ### end Alembic commands ###
