"""adiciona campo fechada em comanda

Revision ID: d68951206161
Revises: 28ff395e795f
Create Date: 2026-07-06 16:52:58.571458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68951206161'
down_revision = '28ff395e795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechada', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.drop_column('fechada')

    # ### end Alembic commands ###
